authors:
  mkdocs-material:
    name: 'Material for MkDocs'
    description: 'The Material Team - A small group of people dedicated to making writing documentation easy, if not outright fun!'
    avatar: https://simpleicons.org/icons/materialformkdocs.svg

  gytxtx:
    name: KFACBT
    description: 'Anyway, keep learning.'
    avatar: https://avatars.githubusercontent.com/u/62281844?v=4
