name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # - run: pip install mkdocs-material==5.5.12
      # - run: pip install mkdocs-material>=5.5.12
      # 安装最新版 MkDocs-Material，且安装额外推荐包
      - run: pip install mkdocs-material>=5.5.12[recommended]

      - run: pip install mkdocs-exclude
      - run: pip install mkdocs-roamlinks-plugin

      # 安装 Blog 插件
      - run: pip install mkdocs-blog-plugin

      # 安装 社交卡片 插件
      - run: pip install mkdocs-social-plugin

      - run: mkdocs gh-deploy --force
